spring:
  application:
    name: myapp

# expose /health and /info endpoints - actuator
management:
  endpoints:
    web:
      exposure:
        include:
          "*"
          # - health
          # - info
          # - metrics
        # exclude: # disable endpoint - actuator
        # - health
        # - info
  info:
    env:
      enabled: true

# add information about our application - actuator
info:
  app:
    name: Healthy Activities
    description: This app keeps tracks of your daily health activities.
    version: 3.0.0

server:
  # setup default port
  port: 9000
